### ISSUE TITLE
Missing edges on expand collapse

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#10]
[sample-graph (7).graphml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/files/10686080/sample-graph.7.graphml.txt)

- collapse 2 of the edges between b & c
- collapse all 3 edges (1 meta & 2 original ones) between b & c
- collapse c3
- collapse c1
- expand c3
- expand c1

I expect edges between b & c to come back (ideally 3 edges, 1 meta & 2 original edges) but none seems to come back.

**Comment by ugurdogrusoz** [comment]
We do get the edges back but rather than 1 meta edge (representing two of the original edges) and 2 original edges, I get all 4 original edges back. Any particular reason we lose that meta edges (representing collapsed edges)?

**Comment by osamazafar980** [comment]
Sire the representation is correct but when we click expandSelectedEdge it calls a function with recursive = true property hence all children meta edges get expanded as well.

**Comment by ugurdogrusoz** [comment]
How about we expose that flag so I can test it when it is false as well.

**Comment by osamazafar980** [comment]
Should we make it so that expandSelectedEdge use recursive = false and expandAll use recursive = true?

**Comment by ugurdogrusoz** [comment]
Those look appropriate default values but we can actually expose the flag in the demo so that people can call expandSelectedEdge with recursive=true and so an as well.

**Comment by osamazafar980** [comment]
Resolved. Added a checkbox called "Recursive Flag (Expand/Collapse Operations)". By default, it will be unchecked and the recursive flag will be False.

Tag effects following operations:
Collapse Selected Nodes, Expand Selected Nodes, Expand Selected Edges, Expand Edges Between Selected Nodes

**Comment by ugurdogrusoz** [comment]
Can we rename the flag label: "Recursive Flag (Expand/Collapse Operations)" => "Recursive (Expand/Collapse Operations)"?

**Comment by osamazafar980** [comment]
Done.
