### ISSUE TITLE
Error on node filtering

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#2]
When you try to move the slider to change filtering values for nodes, you get an error in the console and it does not work.

**Comment by ugurdogrusoz** [comment]
Looks like filtering is fixed but Add random elements throws an error now.

**Comment by ugurdogrusoz** [comment]
Is this fixed @osamazafar980 ?

**Comment by osamazafar980** [comment]
Yes Sir.
