### ISSUE TITLE
Not enough room created on expand

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#21]
Playing with compound sample 2 illustrates that we do not have enough room created for expanding nodes sometimes. This is best observed when "Layout after operation" is unchecked.

**Comment by ugurdogrusoz** [comment]
With the latest changes I think we no longer have this issue.
In fact, currently, there is too much space around the focus node after translation of the coordinates from the component graph in the headless Cytoscape.js. Let's increase the gravity factor and decrease the range (within which gravity is applied). Let's do it for both simple and compound node versions:
// Gravity force (constant)
gravity: 0.25,
// Gravity range (constant) for compounds
gravityRangeCompound: 1.5,
// Gravity force (constant) for compounds
gravityCompound: 1.0,
// Gravity range (constant)
gravityRange: 3.8,

**Comment by ugurdogrusoz** [comment]
Looks like space around the focus node is better. Please state how this was resolved.

**Comment by osamazafar980** [comment]
Following are the layout parameters used for headless layout

          name: 'fcose',
          quality: "proof",
          animate:true,
          animationDuration: 500,
          randomize: false, 
          nodeSeparation: 25,
