### ISSUE TITLE
Incorrect focus graph for expansion factor calculation

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#22]
To determine the expansion factor we lay out the focus graph. Looks like this focus graph show to lower right is not being constructed correctly (using Sample Compound 2):
![Screenshot 2023-04-13 110230](https://user-images.githubusercontent.com/3874988/231694238-9eae08b8-ccad-46e7-8444-ee07dd0fbba0.png)

**Comment by ugurdogrusoz** [comment]
I would also include the expanding compound node itself: n30(20) when constructing this graph

**Comment by osamazafar980** [comment]
Resolved.
