### ISSUE TITLE
Some additional demo options

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#25]
- [x] 1. Under File Operations > Save, add PNG and SVG.
- [x] 2. Create a new section "Graph View" at the end of the sections and add checkboxes "Display node weights", "Display node labels" and "Display edge weights".
- [x] 3. Also under this new section, add "Display node labels:" radio button with choices "Top", "Bottom" and "Middle".

**Comment by osamazafar980** [comment]
Sir, the PNG option is added . Cytoscapejs does not have a built-in export function for SVG format. It can be generated by exporting the PNG image and using the external library to convert it to SVG format. Should we do that?

**Comment by ugurdogrusoz** [comment]
Converting from PNG to SVG is not going to be true vector graphics. Let's just have PNG support for now.

**Comment by osamazafar980** [comment]
PNG support is live and operational.

**Comment by ugurdogrusoz** [comment]
Currently we're only saving the visible graph as PNG but we need to save 2 more graphs (main graph and proxy graph - bottom right one, let's also label this in the demo as "Proxy"):
![image](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/assets/3874988/3220d9a1-02b2-40c3-8568-1e9d99fff460)

**Comment by ugurdogrusoz** [comment]
Can we also increase the font size of label by 1 or 2 (make sure they do fit within the node circles when they have 3-char labels)?

**Comment by ugurdogrusoz** [comment]
Let's also display node labels for compounds *always* on top, regardless of the user setting (otherwise they stay behind child nodes).

**Comment by osamazafar980** [comment]
Resolved.

**Comment by ugurdogrusoz** [comment]
Looks great. The only issue is when you load a new sample/graph, current options are not applied (e.g. middle label)

**Comment by osamazafar980** [comment]
it's fixed.

**Comment by ugurdogrusoz** [comment]
I also noticed that we apply a layout on Load. Can we please disable that? When we save a certain graph, we'd like to see it in the same way sometimes.

**Comment by ugurdogrusoz** [comment]
When you save as PNG, there seems to be additional unnecessary space around the graph. Can we use options to avoid that?

**Comment by ugurdogrusoz** [comment]
I also noticed that the resolution is not very high in png. Please increase that.

**Comment by ugurdogrusoz** [comment]
Options should apply to all graphs, not just the visible one.

**Comment by ugurdogrusoz** [comment]
Remaining issue listed:
- [ ] 4. Options should apply to all graphs, not just the visible one.
- [ ] 5. Resolution is not very hign in png (especially main and proxy ones). Please increase that.
- [ ] 6. When you save as PNG, there seems to be additional unnecessary space around the graph. Can we use options to avoid that?
- [ ] 7. I also noticed that we apply a layout on Load. Can we please disable that? When we save a certain graph, we'd like to see it in the same way sometimes.

**Comment by osamazafar980** [comment]
Updated issues have been resolved, for the transition graph png, please use expand collapse buttons on the left panel instead of cue icons on the nodes.
