### ISSUE TITLE
Proxy graph title

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#27]
Can we title the proxy graph as well? Also make sure the title are all center, left or right aligned please.
![Untitled](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/assets/3874988/02404113-93f6-439d-96b3-825cd0dc545f)

**Comment by osamazafar980** [comment]
Resolved.

**Comment by ugurdogrusoz** [comment]
I don't see the change in the demo?

**Comment by osamazafar980** [comment]
Updated now.
