### ISSUE TITLE
Saving Test Images

### ISSUE THREAD

**Issue by osamazafar980** [iVis-at-Bilkent/cytoscape.js-complexity-management#30]

**Comment by ugurdogrusoz** [comment]
Looks good but make sure neighborhood and proxy graphs have the same style (font size, label location, etc.) as the original one please.

**Comment by osamazafar980** [comment]
SVG Option removed.

**Comment by osamazafar980** [comment]
To generate and save a complete set of PNG images {main graph, interim graphs, and file graph}, expandNode function has to run before saving the PNG images. Otherwise, interim graphs will not be downloaded.

**Comment by ugurdogrusoz** [comment]
![image](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/assets/3874988/fd069ba2-041b-4d8b-8197-71d3f1188afe)

Can we please reduce the font size for this option? No need for bold and radio buttons could be on the same line as the label.
