### ISSUE TITLE
Error on scenario of Fig 5 in paper

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#33]
If you apply the steps of the scenario in Fig 5 of the paper on the attached graph using the visual cues for expand, we get an error.
[fig5.json.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/files/12925473/fig5.json.txt)

**Comment by osamazafar980** [comment]
let nodeID= 'a';
let filter = true;

instance.updateFilterRule((ele) => {
    if(ele.isNode() && ele.id() == nodeID){
        return filter;
    }
    
})

if (document.getElementById("cbk-run-layout3").checked) {
        cy.layout(layoutOptions).run();
  }
  else {
    initializer(cy);
  }
