### ISSUE TITLE
Testing filter/unfilter in demo

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#34]
There is no way to filter or unfilter currently invisible nodes/edges with the demo. This cripples our testing. At least some way to take action from the Console would be ok.

**Comment by osamazafar980** [comment]
let nodeID= 'a';
let filter = true;

instance.updateFilterRule((ele) => {
    if(ele.isNode() && ele.id() == nodeID){
        return filter;
    }
    
})

if (document.getElementById("cbk-run-layout3").checked) {
        cy.layout(layoutOptions).run();
  }
  else {
    initializer(cy);
  }

**Comment by ugurdogrusoz** [comment]
Above code unfilters any filtered code on a new filter so I use the following to filter a set of nodes (this is to filter a & b; to unfilter a, just pass b, etc.):

let nodeIDs = ['a','b'];
let filter = true;

instance.updateFilterRule((ele) => {
  if(ele.isNode() && nodeIDs.includes(ele.id(),0)){
    return filter;
  }
})

if (document.getElementById("cbk-run-layout3").checked) {
  cy.layout(layoutOptions).run();
}
else {
  initializer(cy);
}
