### ISSUE TITLE
Demo related components in source code cause error

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-complexity-management#35]
In the source code of the extension, there are some demo related elements such as [cbk-flag-recursive](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/blob/9e855bc6b49e9f812362676e3ab8e0d966f3e7b6/src/cue-utilities.js#L672), [cbk-run-layout3](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/blob/9e855bc6b49e9f812362676e3ab8e0d966f3e7b6/src/cue-utilities.js#L687) or [cyInvisible](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/blob/9e855bc6b49e9f812362676e3ab8e0d966f3e7b6/src/complexity-management.js#L288) which produce error when the extension is used in other apps. Source code should be cleaned from such elements.

**Comment by osamazafar980** [comment]
We are collecting images in between transitions and steps of expand node and expand graph which requires it to be tuned with demo for now. Once we are done with the paper all those will be removed.

**Comment by hasanbalci** [comment]
Let's not remove them, but comment out for now, because we may need them later.

**Comment by divisuals** [comment]
Any ETA on the fix? This demo/ library is unusable in its current state; more dependencies listed below:
- the layout checkbox (`cbk-run-layout3`) needs to be checked, otherwise it complains of missing `initializer()`

Even with adding these missing checkboxes, the collapsed nodes cannot be expanded; complains of missing `pngImage`. This seems to be a missing definition bug in [cue-utilities](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/blob/main/src/cue-utilities.js), in its `cy.on('tap'...)` function. Adding a global variable, similar to the demo, hides the cues.

I think it is related to using a custom `expandNodes()` instead of the upstream cmgm.

Hope this helps narrowing the problem.

**Comment by osamazafar980** [comment]
Issues Resolved in [publish-ready](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/tree/publish-ready) branch. A lot of usage comments added with original code commented.

**Comment by ugurdogrusoz** [comment]
@divisuals Please use the branch mentioned by @osamazafar980 until a proper release.

**Comment by divisuals** [comment]
Thanks!

I also needed a different layout for my use-case, and this one forces to use `fcose`. Therefore, I landed-up using the older [expand-collapse](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse), and [layers](https://github.com/sgratzl/cytoscape.js-layers) for other annotations.

May have to implement my own headless instance for filtering; will give this another try if I run into dead ends.

🙏

**Comment by osamazafar980** [comment]
@hasanbalci We made fcose as default but it can be changed, right?

**Comment by divisuals** [comment]
Looking at the [default configs](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management?tab=readme-ov-file#default-options) here, doesn't look like layouts are exposed.

expand-collapse has `layoutBy` in its [default configs](https://github.com/iVis-at-Bilkent/cytoscape.js-expand-collapse/tree/master?tab=readme-ov-file#default-options), which is what I'm using. It also has undo-redo and fisheye though not yet relevant for me.

Seems this extension targets to add more functionality but currently doesn't expose as many configs yet.

My $0.02...

**Comment by ugurdogrusoz** [comment]
the framework could support other layouts but the current implementation does not allow this.
any particular reason you need a different layout? what layout is it if you don't mind me asking?

**Comment by divisuals** [comment]
Of course! My use case is rendering DAGs, so started with klay but now using [elkjs](https://github.com/cytoscape/cytoscape.js-elk) with good results... still a lot to build!

For some local tests, I could hack together the bundle file globally replacing fcose, but prefer it is supported cleanly, just like expand-collapse.
No rush on this; happy to raise a separate (low-priority) enhancement request for it.

If this bundle is tested, you can close this out for now.
