### ISSUE TITLE
Package not available on NPM

### ISSUE THREAD

**Issue by svozza** [iVis-at-Bilkent/cytoscape.js-complexity-management#37]
The README contains instructions to install the package using NPM:

```sh
npm install cytoscape-complexity-management
```

However, this fails because the package is not available. Might be worthwhile adding a note saying that the package hasn't been released yet.

**Comment by hasanbalci** [comment]
@svozza We added a note now, sorry for the inconvenience.

**Comment by svozza** [comment]
Good stuff!
