### ISSUE TITLE
Bug on node expand

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-complexity-management#4]
- First collapse edges between d and e
- Then collapse and expand c4
- Collapse edges between d and 4 should come back as collapsed, but they come back as expanded 

https://user-images.githubusercontent.com/22586369/213388958-da256565-3582-4e1f-8fbe-b2deaef60eb8.mp4

**Comment by osamazafar980** [comment]
Resolved
