### ISSUE TITLE
Error on expand collapse

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-complexity-management#8]
- load the following graph
- collapse the 3 edges between f & g
- collapse c3
- collapse c2 and you get an error (see the console)
[sample-graph (7).graphml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/files/10662363/sample-graph.7.graphml.txt)

**Comment by osamazafar980** [comment]
graph file is missing
