### ISSUE TITLE
Meta Edge inconsistancy

### ISSUE THREAD

**Issue by osamazafar980** [iVis-at-Bilkent/cytoscape.js-complexity-management#9]
Load Graph Ml file    [BUG.graphml.txt](https://github.com/iVis-at-Bilkent/cytoscape.js-complexity-management/files/10684731/BUG.graphml.txt)
Collapse all nodes
Expand c3

Meta Edge is inconsistent (should be b/w c1 & c4).

**Comment by osamazafar980** [comment]
Resolved

**Comment by ugurdogrusoz** [comment]
I am getting an error when applying the exact scenario above. I don't see a linked commit to this issues either.

**Comment by osamazafar980** [comment]
Similar Bug Found

Add 2 edges between Node d and g
check recursive flag
Collapse c3
collapse all edges
uncheck recursive flag
expand c3

MetaEdges are inconsistent.
